spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/book_manager
    hikari:
      username: root
      password: a1s2d3A!S@
server:
  port: 8070

